version: "3.7"
services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
      ports:
       - "9200:9200"
       - "9300:9300"
      environment:
        - discovery.type=single-node

    kibana:
      image: docker.elastic.co/kibana/kibana:7.8.0
      ports:
       - "5601:5601"
      links:
       - elasticsearch
    logstash:
      build: logstash
      command: logstash -f logstash.conf
      ports:
       - "5043:5043"
       - "5044:5044"
      links:
       - elasticsearch
    logger_service:
      build:
        context: ./spring-boot-app
      ports:
        - "8080:8080"
      links:
       - logstash
